# Generated by Django 5.1.2 on 2025-03-06 18:25

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_national_id_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BD', unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +8801XXXXXXXXX (11 digits)', regex='^\\+?880\\d{9}$')], verbose_name='Phone number'),
        ),
    ]
