# Generated by Django 5.1.7 on 2025-03-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
