# Generated by Django 5.1.7 on 2025-03-08 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_bloodrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='donor',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='donors',
            field=models.ManyToManyField(related_name='requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='total_accepted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
