# Generated by Django 5.1.7 on 2025-03-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_remove_bloodrequest_donor_bloodrequest_donors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
    ]
