# Generated by Django 5.1.7 on 2025-03-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_remove_bloodrequest_accepted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='aaccepted_donors',
            new_name='accepted_donors',
        ),
    ]
