# Generated by Django 5.1.7 on 2025-03-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0009_rename_aaccepted_donors_bloodrequest_accepted_donors'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='detail_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
