# Generated by Django 5.1.7 on 2025-03-09 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0010_bloodrequest_description_bloodrequest_detail_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='rejected',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='final_donors',
            field=models.ManyToManyField(blank=True, related_name='final_donors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='rejected_donors_by_requester',
            field=models.ManyToManyField(blank=True, related_name='rejected_donor_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
