# Generated by Django 5.1.7 on 2025-03-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0013_helprequester'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequester',
            name='blood_request_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=10),
        ),
    ]
