# Generated by Django 5.1.7 on 2025-03-12 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0015_alter_helprequester_helper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequester',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper', to='donors.donorprofile'),
        ),
        migrations.AlterField(
            model_name='helprequester',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='donors.donorprofile'),
        ),
    ]
