# Generated by Django 5.1.7 on 2025-03-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0016_alter_helprequester_helper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequester',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
