# Generated by Django 5.1.7 on 2025-03-15 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0017_helprequester_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('accepted_count', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_accepted', models.IntegerField(blank=True, default=0, null=True)),
                ('detail_address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('donation_date', models.DateField(blank=True, null=True)),
                ('donation_time', models.TimeField(blank=True, null=True)),
                ('receiver_latitude', models.FloatField(blank=True, null=True)),
                ('receiver_longitude', models.FloatField(blank=True, null=True)),
                ('accepted_donors', models.ManyToManyField(blank=True, related_name='accepted_custom_requests', to=settings.AUTH_USER_MODEL)),
                ('donors', models.ManyToManyField(related_name='custom_requests_received', to=settings.AUTH_USER_MODEL)),
                ('final_donors', models.ManyToManyField(blank=True, related_name='custom_final_donors', to=settings.AUTH_USER_MODEL)),
                ('rejected_donors_by_requester', models.ManyToManyField(blank=True, related_name='rejected_custom_donor_request', to=settings.AUTH_USER_MODEL)),
                ('request_ignored_by_donors', models.ManyToManyField(blank=True, related_name='ignored_custom_donors', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
