# Generated by Django 5.1.2 on 2025-04-29 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0018_custombloodrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequester',
            name='blood_request_id',
        ),
        migrations.AddField(
            model_name='helprequester',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='donors.bloodrequest'),
        ),
    ]
