# Generated by Django 5.1.2 on 2025-04-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0019_remove_helprequester_blood_request_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequester',
            name='blood_request',
        ),
        migrations.AddField(
            model_name='helprequester',
            name='blood_request_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=10),
        ),
    ]
