# Generated by Django 5.1.2 on 2025-05-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0020_remove_helprequester_blood_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='detailed_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
